<?php
declare(strict_types=1);

// KiprioHttpApis SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

KiprioHttpApisUtility::setRegistrar(function (KiprioHttpApisUtility $u): void {
    $u->clean = [KiprioHttpApisClean::class, 'call'];
    $u->done = [KiprioHttpApisDone::class, 'call'];
    $u->make_error = [KiprioHttpApisMakeError::class, 'call'];
    $u->feature_add = [KiprioHttpApisFeatureAdd::class, 'call'];
    $u->feature_hook = [KiprioHttpApisFeatureHook::class, 'call'];
    $u->feature_init = [KiprioHttpApisFeatureInit::class, 'call'];
    $u->fetcher = [KiprioHttpApisFetcher::class, 'call'];
    $u->make_fetch_def = [KiprioHttpApisMakeFetchDef::class, 'call'];
    $u->make_context = [KiprioHttpApisMakeContext::class, 'call'];
    $u->make_options = [KiprioHttpApisMakeOptions::class, 'call'];
    $u->make_request = [KiprioHttpApisMakeRequest::class, 'call'];
    $u->make_response = [KiprioHttpApisMakeResponse::class, 'call'];
    $u->make_result = [KiprioHttpApisMakeResult::class, 'call'];
    $u->make_point = [KiprioHttpApisMakePoint::class, 'call'];
    $u->make_spec = [KiprioHttpApisMakeSpec::class, 'call'];
    $u->make_url = [KiprioHttpApisMakeUrl::class, 'call'];
    $u->param = [KiprioHttpApisParam::class, 'call'];
    $u->prepare_auth = [KiprioHttpApisPrepareAuth::class, 'call'];
    $u->prepare_body = [KiprioHttpApisPrepareBody::class, 'call'];
    $u->prepare_headers = [KiprioHttpApisPrepareHeaders::class, 'call'];
    $u->prepare_method = [KiprioHttpApisPrepareMethod::class, 'call'];
    $u->prepare_params = [KiprioHttpApisPrepareParams::class, 'call'];
    $u->prepare_path = [KiprioHttpApisPreparePath::class, 'call'];
    $u->prepare_query = [KiprioHttpApisPrepareQuery::class, 'call'];
    $u->graphql_body = [KiprioHttpApisGraphql::class, 'body'];
    $u->graphql_errors = [KiprioHttpApisGraphql::class, 'errors'];
    $u->result_basic = [KiprioHttpApisResultBasic::class, 'call'];
    $u->result_body = [KiprioHttpApisResultBody::class, 'call'];
    $u->result_headers = [KiprioHttpApisResultHeaders::class, 'call'];
    $u->transform_request = [KiprioHttpApisTransformRequest::class, 'call'];
    $u->transform_response = [KiprioHttpApisTransformResponse::class, 'call'];
});
